CREATE TABLE REFUND(
    REFUND_CODE         VARCHAR2(12),
    NUM                 NUMBER(6),
    ID                  VARCHAR2(20),
    PRODUCT_CODE        VARCHAR2(30),
    REFUND_AMOUNT       NUMBER(4) CHECK (REFUND_AMOUNT>0),
    REFUND_DATE         TIMESTAMP DEFAULT SYSDATE,
    REFUND_STATUS       VARCHAR2(100),
    CONSTRAINT REFUND_CODE_PK PRIMARY KEY(REFUND_CODE),
    CONSTRAINT REFUND_ID_FK   FOREIGN KEY(ID) REFERENCES MEMBER(ID),
    CONSTRAINT REFUND_PRODUCT_CODE_FK FOREIGN KEY(PRODUCT_CODE) REFERENCES PRODUCT(PRODUCT_CODE)
    );