CREATE TABLE PRODUCT(
    NUM                 NUMBER(4),
    PRODUCT_CODE        VARCHAR2(30),
    PRODUCT_COMPANY     VARCHAR2(50) NOT NULL,
    PRODUCT_NAME        VARCHAR2(200) NOT NULL,
    PRODUCT_PRICE       NUMBER(8) CHECK (PRODUCT_PRICE >= 0),
    PRODUCT_AMOUNT      NUMBER(4) CHECK (PRODUCT_AMOUNT > 0),
   	IMG_NAME			VARCHAR2(300),
    CONSTRAINT PRODUCT_PRODUCT_CODE_PK PRIMARY KEY(PRODUCT_CODE)
    );
    
create sequence product_seq
start with 1
increment by 1
maxvalue 9999
;